address_list:
    path:     /
    defaults: { _controller: AppBundle\Controller\AddressBookController::showAddressListAction }
add_address:
    path:     /address/add
    defaults: { _controller: AppBundle\Controller\AddressBookController::addAddressAction }
edit_address:
    path:     /address/edit/{id}
    defaults: { _controller: AppBundle\Controller\AddressBookController::editAddressAction }
remove_address:
    path:     /address/delete/{id}
    defaults: { _controller: AppBundle\Controller\AddressBookController::removeAddressAction }
address_overview:
    path:     /overview
    defaults: { _controller: AppBundle\Controller\AddressBookController::showOverviewAction }